// <auto-generated />
using System.Collections.Generic;
using FantasyNameAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FantasyNameAPI.Database.Migrations
{
    [DbContext(typeof(FantasyNameApiContext))]
    partial class FantasyNameApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("FantasyNameAPI.Models.FantasyModel", b =>
                {
                    b.Property<string>("Race")
                        .HasColumnType("text")
                        .HasColumnName("race");

                    b.Property<List<string>>("Descriptions")
                        .HasColumnType("text[]")
                        .HasColumnName("descriptions");

                    b.Property<List<string>>("Names")
                        .HasColumnType("text[]")
                        .HasColumnName("names");

                    b.HasKey("Race")
                        .HasName("pk_fantasy_items");

                    b.ToTable("fantasy_items");
                });
#pragma warning restore 612, 618
        }
    }
}
